### ISSUE TITLE
Infrastructure set up

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#37]
What environments are need it?

- [x] Spark cluster (`aws-spark-*`)
- [x] HDFS cluster
- [x] image-service
- [x] Cassandra
- [x] SOLR (`aws-quoll-*`)
- [x] Zookeeper (`aws-quoll-zoo-*`)
- [x] biocache-service (`aws-spark-demo`)
- [x] ala-hub test (`aws-spark-demo`)

**Comment by javier-molina** [comment]
Does all of it need to be set up straight away?

**Comment by ansell** [comment]
The existing `auth-test` and `logger-test` systems should be able to be reused, but the others above have interactions that rule out being able to reuse the existing test instances during isolated testing of the new set of systems. 

The skinned hub can be setup later on, as it is lower risk, but still needs to be verified during testing.

**Comment by javier-molina** [comment]
Thanks @ansell for thinking upfront in all the testing that needs to be performed and the environments need it.

I just realised that the epic functionality is only provided by ZenHub. I'm more inclined to resurrect it. In the meantime I will create separate tickets for what we need for Sprint 1.
