### ISSUE TITLE
post pipelines implementation task list

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#444]
- [ ] run and schedule ANWC job - weekly (Doug)
- [ ] schedule iNaturalist - Monday night (Peggy)
- [ ] schedule QG - Friday night (Peggy)
- [ ] schedule Bionet - weekly (Patricia)
- [ ] migrate and schedule BioCollect - daily (Mahmoud)
